"""sync models with ORM

Revision ID: 5b2a7884f027
Revises: 6cbb6e1faef6
Create Date: 2025-12-05 02:22:46.443667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2a7884f027'
down_revision: Union[str, Sequence[str], None] = '6cbb6e1faef6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=11),
            server_default=None,
            existing_nullable=False,
        )
        batch_op.create_foreign_key(
            'fk_leads_user_id_users',  # ← ИМЯ КОНСТРЕЙНТА
            'users',                   # целевая таблица
            ['user_id'],               # локальный столбец
            ['id'],                    # внешний столбец
            # при желании можно добавить ondelete='SET NULL' или 'CASCADE'
        )


    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('1'),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'CLIENT'"),
               existing_nullable=False)


    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_leads_user_id_users',  # ← то же самое имя
            type_='foreignkey',
        )
        batch_op.alter_column(
            'status',
            existing_type=sa.VARCHAR(length=11),
            server_default=sa.text("'NEW'"),
            existing_nullable=False,
        )


    # ### end Alembic commands ###
